version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
after_build:
- cmd: 7z a %APPVEYOR_PROJECT_NAME%_v%APPVEYOR_BUILD_VERSION%.zip -r %APPVEYOR_BUILD_FOLDER%\esCharView\bin\Release\*.* -x!*.pdb
artifacts:
- path: '*.zip'
  name: esCharView_v${APPVEYOR_BUILD_VERSION}
  type: WebDeployPackage
deploy:
- provider: Environment
  name: Github
  on:
    branch: master